name: Detaxine Charts GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: ["main"]

permissions:
  checks: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  SOURCE_CODE_PATH: "src/core/examples/"

jobs:
  check_source_code_changes:
    runs-on: ubuntu-latest
    outputs:
      should_publish: ${{ steps.confirm_changes.outputs.SHOULD_PUBLISH }}

    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - id: file_changes
        name: Check for Source Code Changes
        run: |
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.sha }}"
          files_temp=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          files=$(echo "$files_temp" | tr "\n" " ")
          echo "changed_files=$files" >> "$GITHUB_OUTPUT"

      - id: confirm_changes
        name: Confirm Changes
        shell: bash
        run: |
          echo "Changed files: ${{ steps.file_changes.outputs.changed_files }}"
          echo "If you see here files that you have not modified, please update your branch with changes from main."

          # Check if the modified files include this path
          if echo "${{ steps.file_changes.outputs.changed_files }}" | grep -q "${{ env.SOURCE_CODE_PATH }}"; then
            # Set the output variable and exit the loop
            echo "triggering_path is ${{ env.SOURCE_CODE_PATH }}"
            echo "SHOULD_PUBLISH=true" >> "$GITHUB_OUTPUT"
            cat "$GITHUB_OUTPUT"
          else
            echo "SHOULD_PUBLISH=false" >> "$GITHUB_OUTPUT"

          fi

          exit 0

  deploy:
    runs-on: ubuntu-latest
    needs: [check_source_code_changes]
    if: ${{ needs.check_source_code_changes.outputs.should_publish == 'true' }}
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v6

      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal
      - name: Install Trunk
        uses: jetli/trunk-action@v0.5.1
        with:
          version: latest
      - name: Build dashboard
        working-directory: src/core
        run: trunk build --example dashboard --release --public-url /detaxine-charts/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src/core/dist
