name: Detaxine Charts CI
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: ["main"]

permissions:
  checks: write
  contents: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  SOURCE_CODE_PATH: "src/core/src/"
jobs:
  check_source_code_changes:
    runs-on: ubuntu-latest
    outputs:
      should_publish: ${{ steps.confirm_changes.outputs.SHOULD_PUBLISH }}

    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - id: file_changes
        name: Check for Source Code Changes
        run: |
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.sha }}"
          files_temp=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          files=$(echo "$files_temp" | tr "\n" " ")
          echo "changed_files=$files" >> "$GITHUB_OUTPUT"

      - id: confirm_changes
        name: Confirm Changes
        shell: bash
        run: |
          echo "Changed files: ${{ steps.file_changes.outputs.changed_files }}"
          echo "If you see here files that you have not modified, please update your branch with changes from main."

          # Check if the modified files include this path
          if echo "${{ steps.file_changes.outputs.changed_files }}" | grep -q "${{ env.SOURCE_CODE_PATH }}"; then
            # Set the output variable and exit the loop
            echo "triggering_path is ${{ env.SOURCE_CODE_PATH }}"
            echo "SHOULD_PUBLISH=true" >> "$GITHUB_OUTPUT"
            cat "$GITHUB_OUTPUT"
          else
            echo "SHOULD_PUBLISH=false" >> "$GITHUB_OUTPUT"

          fi

          exit 0
  tests:
    runs-on: ubuntu-latest
    needs: [check_source_code_changes]
    if: ${{ needs.check_source_code_changes.outputs.should_publish == 'true' }}
    steps:
      - uses: actions/checkout@v6
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Run tests
        working-directory: src/core
        run: wasm-pack test --firefox --headless

  publish:
    needs: [tests, check_source_code_changes]
    if: |
      always() &&
      (needs.tests.result != 'failure' && needs.check_source_code_changes.outputs.should_publish == 'true')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal
      - name: Publish to crates.io
        working-directory: src/core
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: cargo publish

  automerge:
    runs-on: ubuntu-latest
    needs: [tests, publish]
    if: |
      always() &&
      (needs.tests.result != 'failure' && needs.publish.result != 'failure')
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
